---
application:
  name: "team-10-python-project"
  project: "random-test"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "django db"
routers:
- name: "main-team-10-python-project"
  routes:
  - application_name: "team-10-python-project"
    paths:
    - "/*"
