# Generated by Django 3.2.5 on 2021-08-13 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_profile_avatar'),
        ('classes', '0004_alter_upload_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='key_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='home.classes'),
        ),
    ]
