# Generated by Django 3.2.5 on 2021-08-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_classinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinvitation',
            name='email',
            field=models.EmailField(max_length=420, verbose_name='email_address'),
        ),
    ]
