# Generated by Django 3.2.5 on 2021-08-24 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_classtime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassTime',
        ),
    ]
