# Generated by Django 3.2.6 on 2021-09-12 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAnnouncementDiscord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(max_length=400)),
                ('message', models.TextField(default='Class - {0}\nSubject - {1}\nDay - {2}\nLink - [here]({3})', max_length=120)),
                ('key_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='home.classes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
