# Generated by Django 3.2.6 on 2021-10-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_squashed_0009_delete_classtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
