# Generated by Django 3.2.5 on 2021-08-18 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_profile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0005_alter_assignment_key_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False, verbose_name='accepted')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='key')),
                ('sent', models.DateTimeField(null=True, verbose_name='sent')),
                ('email', models.EmailField(max_length=420, unique=True, verbose_name='email_address')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('invited_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitees', to='home.classes')),
                ('inviter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
