name: Merge me!
# https://stefanzweifel.io/posts/2021/04/28/auto-merge-dependabot-pull-requests
# Automerge Dependabot pull requests
on:
    workflow_run:
        types:
            - completed
        workflows:
            - 'Python package'

jobs:
    merge-me:
        name: Merge me!

        runs-on: ubuntu-latest

        steps:
            - name: Merge me!
              if: ${{ github.event.workflow_run.conclusion == 'success' }}
              uses: ridedott/merge-me-action@v2
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  PRESET: DEPENDABOT_MINOR
                  MAXIMUM_RETRIES: 2
